Repository BE-Friend-Develop-Team/detour, pull requests merged in 2024-07, with the labels that each got.

#5 [2024/07/24] feature/user/auth >> 인증/인가(로그인, 로그아웃, 회원가입) 구현
  build.gradle
  http/1. 회원 가입.http
  http/2. 로그인, 로그아웃.http
  http/3. 회원탈퇴.http
  src/main/java/com/befriend/detour/DetourApplication.java
  src/main/java/com/befriend/detour/domain/user/controller/UserController.java
  src/main/java/com/befriend/detour/domain/user/dto/LoginRequestDto.java
  src/main/java/com/befriend/detour/domain/user/dto/SignupRequestDto.java
  src/main/java/com/befriend/detour/domain/user/entity/User.java
  src/main/java/com/befriend/detour/domain/user/entity/UserRoleEnum.java
  src/main/java/com/befriend/detour/domain/user/repository/UserRepository.java
  src/main/java/com/befriend/detour/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/befriend/detour/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/befriend/detour/domain/user/service/UserDetailsServiceImpl.java
  src/main/java/com/befriend/detour/domain/user/service/UserService.java
  src/main/java/com/befriend/detour/global/config/JpaConfig.java
  src/main/java/com/befriend/detour/global/config/SecurityConfig.java
  src/main/java/com/befriend/detour/global/config/WebSecurityConfig.java
  src/main/java/com/befriend/detour/global/dto/SecurityResponse.java
  src/main/java/com/befriend/detour/global/exception/ErrorCode.java
  src/main/java/com/befriend/detour/global/jwt/JwtProvider.java
  src/main/java/com/befriend/detour/global/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/befriend/detour/global/security/JwtAuthenticationFilter.java
  src/main/java/com/befriend/detour/global/security/JwtAuthorizationFilter.java
  src/main/java/com/befriend/detour/global/security/UserDetailsImpl.java
Labels: ✨ feat, ♻️ refactor, 🩹 fix

#13 [2024/07/23] feature/schedule/crud >> Schedule 생성 기능 구현
  http/4. 일정.http
  src/main/java/com/befriend/detour/domain/invitation/repository/InvitationRepository.java
  src/main/java/com/befriend/detour/domain/schedule/controller/ScheduleController.java
  src/main/java/com/befriend/detour/domain/schedule/dto/ScheduleRequestDto.java
  src/main/java/com/befriend/detour/domain/schedule/dto/ScheduleResponseDto.java
  src/main/java/com/befriend/detour/domain/schedule/entity/Schedule.java
  src/main/java/com/befriend/detour/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/befriend/detour/domain/schedule/service/ScheduleService.java
Labels: ✨ feat, ❓ question

#19 [2024/07/23] feature/dailyplan/cr >> DailyPlan 생성 기능 구현
  http/5. 데일리플랜.http
  src/main/java/com/befriend/detour/domain/dailyplan/controller/DailyPlanController.java
  src/main/java/com/befriend/detour/domain/dailyplan/dto/DailyPlanRequestDto.java
  src/main/java/com/befriend/detour/domain/dailyplan/entity/DailyPlan.java
  src/main/java/com/befriend/detour/domain/dailyplan/repository/DailyPlanRepository.java
  src/main/java/com/befriend/detour/domain/dailyplan/service/DailyPlanService.java
  src/main/java/com/befriend/detour/domain/schedule/service/ScheduleService.java
  src/main/java/com/befriend/detour/global/exception/ErrorCode.java
Labels: ✨ feat

#18 [2024/07/23] feature/marker/cu, rd >> Marker 기능 구현
  .gitignore
  http/5. 마커.http
  src/main/java/com/befriend/detour/domain/dailyplan/service/DailyPlanService.java
  src/main/java/com/befriend/detour/domain/marker/controller/MarkerController.java
  src/main/java/com/befriend/detour/domain/marker/dto/MarkerContentRequestDto.java
  src/main/java/com/befriend/detour/domain/marker/dto/MarkerRequestDto.java
  src/main/java/com/befriend/detour/domain/marker/dto/MarkerResponseDto.java
  src/main/java/com/befriend/detour/domain/marker/entity/Marker.java
  src/main/java/com/befriend/detour/domain/marker/entity/MarkerStatusEnum.java
  src/main/java/com/befriend/detour/domain/marker/repository/MarkerRepository.java
  src/main/java/com/befriend/detour/domain/marker/repository/MarkerRepositoryCustom.java
  src/main/java/com/befriend/detour/domain/marker/repository/MarkerRepositoryImpl.java
  src/main/java/com/befriend/detour/domain/marker/service/MarkerService.java
  src/main/java/com/befriend/detour/domain/user/entity/UserStatusEnum.java
  src/main/java/com/befriend/detour/domain/user/service/UserDetailsServiceImpl.java
  src/main/java/com/befriend/detour/global/exception/ErrorCode.java
Labels: ✨ feat

#21 [2024/07/24] feature/user/social-login >> 카카오톡 소셜 로그인 구현
  src/main/java/com/befriend/detour/domain/user/controller/UserController.java
  src/main/java/com/befriend/detour/domain/user/dto/KaKaoUserInfoDto.java
  src/main/java/com/befriend/detour/domain/user/entity/User.java
  src/main/java/com/befriend/detour/domain/user/repository/UserRepository.java
  src/main/java/com/befriend/detour/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/befriend/detour/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/befriend/detour/domain/user/service/KakaoService.java
  src/main/java/com/befriend/detour/global/config/RestTemplateConfig.java
  src/main/java/com/befriend/detour/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: ✨ feat

#29 [2024/07/24] feature/dailyplan/cr >> DailyPlan 조회 기능 구현
  http/5. 데일리플랜.http
  src/main/java/com/befriend/detour/domain/dailyplan/controller/DailyPlanController.java
  src/main/java/com/befriend/detour/domain/dailyplan/dto/DailyPlanResponseDto.java
  src/main/java/com/befriend/detour/domain/dailyplan/repository/DailyPlanRepository.java
  src/main/java/com/befriend/detour/domain/dailyplan/service/DailyPlanService.java
Labels: ✨ feat

#31 [2024/07/24] feature/user/get-edit-profile >> 유저 조회, 프로필 수정 기능 구현
  http/7. 프로필 조회, 수정.http
  src/main/java/com/befriend/detour/domain/user/controller/UserController.java
  src/main/java/com/befriend/detour/domain/user/dto/EditEmailRequestDto.java
  src/main/java/com/befriend/detour/domain/user/dto/EditNicknameRequestDto.java
  src/main/java/com/befriend/detour/domain/user/dto/EditPasswordDto.java
  src/main/java/com/befriend/detour/domain/user/dto/ProfileResponseDto.java
  src/main/java/com/befriend/detour/domain/user/entity/User.java
  src/main/java/com/befriend/detour/domain/user/service/UserService.java
  src/main/java/com/befriend/detour/global/exception/ErrorCode.java
Labels: ✨ feat

#34 [2024/07/25] feature/schedule/crud >> 일행 초대 및 취소 기능 구현
  http/1. 회원 가입.http
  http/2. 로그인, 로그아웃.http
  http/4. 일정.http
  src/main/java/com/befriend/detour/domain/invitation/repository/InvitationRepository.java
  src/main/java/com/befriend/detour/domain/invitation/repository/InvitationRepositoryCustom.java
  src/main/java/com/befriend/detour/domain/invitation/repository/InvitationRepositoryImpl.java
  src/main/java/com/befriend/detour/domain/schedule/controller/ScheduleController.java
  src/main/java/com/befriend/detour/domain/schedule/dto/InvitationRequestDto.java
  src/main/java/com/befriend/detour/domain/schedule/service/ScheduleService.java
  src/main/java/com/befriend/detour/global/exception/ErrorCode.java
Labels: ✨ feat, ♻️ refactor

#35 [2024/07/25] feature/admin >> Admin 기능 구현
  http/8. Admin 기능.http
  src/main/java/com/befriend/detour/domain/user/controller/AdminController.java
  src/main/java/com/befriend/detour/domain/user/dto/ProfileResponseDto.java
  src/main/java/com/befriend/detour/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/befriend/detour/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/befriend/detour/domain/user/service/AdminService.java
  src/main/java/com/befriend/detour/domain/user/service/UserService.java
  src/main/java/com/befriend/detour/global/exception/ErrorCode.java
Labels: ✨ feat

#37 [2024/07/25] feature/token-refresh >> 액세스 토큰 재발급 기능 구현
  http/9. 액세스 토큰 재발급.http
  src/main/java/com/befriend/detour/domain/user/controller/UserController.java
  src/main/java/com/befriend/detour/domain/user/dto/EditPasswordRequestDto.java
  src/main/java/com/befriend/detour/domain/user/dto/RefreshAccessTokenRequestDto.java
  src/main/java/com/befriend/detour/domain/user/service/UserService.java
  src/main/java/com/befriend/detour/global/exception/ErrorCode.java
Labels: ✨ feat

#38 [2024/07/25] feature/schedule/like >> 일정 좋아요 관련 기능 구현
  http/4. 일정.http
  src/main/java/com/befriend/detour/domain/like/controller/LikeController.java
  src/main/java/com/befriend/detour/domain/like/entity/Like.java
  src/main/java/com/befriend/detour/domain/like/repository/LikeRepository.java
  src/main/java/com/befriend/detour/domain/like/repository/LikeRepositoryCustom.java
  src/main/java/com/befriend/detour/domain/like/repository/LikeRepositoryImpl.java
  src/main/java/com/befriend/detour/domain/like/service/LikeService.java
  src/main/java/com/befriend/detour/global/exception/ErrorCode.java
Labels: ✨ feat

#43 [2024/07/25] feature/schedule/crud >> Schedule 수정 및 삭제 관련 기능 구현
  http/4. 일정.http
  src/main/java/com/befriend/detour/domain/schedule/controller/ScheduleController.java
  src/main/java/com/befriend/detour/domain/schedule/dto/EditDateRequestDto.java
  src/main/java/com/befriend/detour/domain/schedule/dto/EditMainImageRequestDto.java
  src/main/java/com/befriend/detour/domain/schedule/dto/EditTitleRequestDto.java
  src/main/java/com/befriend/detour/domain/schedule/dto/ScheduleResponseDto.java
  src/main/java/com/befriend/detour/domain/schedule/entity/Schedule.java
  src/main/java/com/befriend/detour/domain/schedule/service/ScheduleService.java
Labels: ✨ feat, ♻️ refactor

#41 [2024/07/25] feature/marker/rd >> Marker S3를 통한 이미지 관련 기능 구현
  build.gradle
  http/10. 장소.http
  http/5. 마커.http
  http/6. 마커.http
  src/main/java/com/befriend/detour/domain/file/entity/File.java
  src/main/java/com/befriend/detour/domain/file/repository/FileRepository.java
  src/main/java/com/befriend/detour/domain/file/service/FileService.java
  src/main/java/com/befriend/detour/domain/marker/controller/MarkerController.java
  src/main/java/com/befriend/detour/domain/marker/dto/MarkerLocationResponseDto.java
  src/main/java/com/befriend/detour/domain/marker/dto/MarkerRequestDto.java
  src/main/java/com/befriend/detour/domain/marker/dto/MarkerResponseDto.java
  src/main/java/com/befriend/detour/domain/marker/entity/Marker.java
  src/main/java/com/befriend/detour/domain/marker/repository/MarkerRepositoryImpl.java
  src/main/java/com/befriend/detour/domain/marker/service/MarkerFileService.java
  src/main/java/com/befriend/detour/domain/marker/service/MarkerService.java
  src/main/java/com/befriend/detour/global/config/S3Config.java
  src/main/java/com/befriend/detour/global/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: ✨ feat

#44 [2024/07/25] feature/docker >> 배포를 위한 도커파일 생성
  Dockerfile
Labels: ✨ feat

#46 [2024/07/25] feature/schedule/crud >> 초대 관련 기능 코드 위치 이동
  src/main/java/com/befriend/detour/domain/invitation/controller/InvitationController.java
  src/main/java/com/befriend/detour/domain/invitation/dto/InvitationRequestDto.java
  src/main/java/com/befriend/detour/domain/invitation/service/InvitationService.java
  src/main/java/com/befriend/detour/domain/schedule/controller/ScheduleController.java
  src/main/java/com/befriend/detour/domain/schedule/service/ScheduleService.java
Labels: ♻️ refactor

#47 [2024/07/26] feature/auth/email-authentication >> 이메일 인증 기능 구현
  build.gradle
  http/10. 이메일 인증.http
  src/main/java/com/befriend/detour/domain/user/controller/UserController.java
  src/main/java/com/befriend/detour/domain/user/dao/CertificationNumberDao.java
  src/main/java/com/befriend/detour/domain/user/dto/UserCertificateAccountRequestDto.java
  src/main/java/com/befriend/detour/domain/user/service/EmailCertificationService.java
  src/main/java/com/befriend/detour/global/config/RedisConfig.java
  src/main/java/com/befriend/detour/global/config/SecurityConfig.java
  src/main/java/com/befriend/detour/global/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: ✨ feat

#48 [2024/07/26] feature/marker/rd >> Marker 전체 조회, 단건 조회 기능 수정
  http/6. 마커.http
  src/main/java/com/befriend/detour/domain/marker/repository/MarkerRepositoryCustom.java
  src/main/java/com/befriend/detour/domain/marker/repository/MarkerRepositoryImpl.java
  src/main/java/com/befriend/detour/domain/marker/service/MarkerService.java
Labels: ♻️ refactor

#51 [2024/07/29] feature/marker/rd >> 튜터님 피드백 기반 코드 수정
  src/main/java/com/befriend/detour/domain/file/service/FileService.java
  src/main/java/com/befriend/detour/domain/marker/controller/MarkerController.java
  src/main/java/com/befriend/detour/domain/marker/dto/MarkerLocationResponseDto.java
  src/main/java/com/befriend/detour/domain/marker/dto/MarkerResponseDto.java
  src/main/java/com/befriend/detour/domain/marker/entity/Marker.java
  src/main/java/com/befriend/detour/domain/marker/entity/MarkerStatusEnum.java
  src/main/java/com/befriend/detour/domain/marker/repository/MarkerRepository.java
  src/main/java/com/befriend/detour/domain/marker/repository/MarkerRepositoryImpl.java
  src/main/java/com/befriend/detour/domain/marker/service/MarkerService.java
  src/main/java/com/befriend/detour/domain/user/service/UserService.java
  src/main/java/com/befriend/detour/global/exception/ErrorCode.java
Labels: ♻️ refactor

#53 [2024/07/29] feature/schedule/crud >> Schedule 관련 코드 리팩토링
  http/4. 일정.http
  http/5. 데일리플랜.http
  src/main/java/com/befriend/detour/domain/dailyplan/controller/DailyPlanController.java
  src/main/java/com/befriend/detour/domain/schedule/dto/EditDateRequestDto.java
  src/main/java/com/befriend/detour/domain/schedule/dto/ScheduleRequestDto.java
  src/main/java/com/befriend/detour/domain/schedule/dto/ScheduleResponseDto.java
  src/main/java/com/befriend/detour/domain/schedule/entity/Schedule.java
  src/main/java/com/befriend/detour/domain/schedule/service/ScheduleService.java
Labels: ♻️ refactor

#55 [2024/07/29] feature/schedule/like >> 좋아요 관련 코드 리팩토링
  src/main/java/com/befriend/detour/domain/like/entity/Like.java
  src/main/java/com/befriend/detour/domain/like/repository/LikeRepositoryCustom.java
  src/main/java/com/befriend/detour/domain/like/repository/LikeRepositoryImpl.java
  src/main/java/com/befriend/detour/domain/like/service/LikeService.java
Labels: ♻️ refactor

#57 [2024/07/29] feature/schedule/crud >> Invitation 및 Schedule 리팩토링
  http/4. 일정.http
  src/main/java/com/befriend/detour/domain/invitation/repository/InvitationRepository.java
  src/main/java/com/befriend/detour/domain/invitation/repository/InvitationRepositoryCustom.java
  src/main/java/com/befriend/detour/domain/invitation/repository/InvitationRepositoryImpl.java
  src/main/java/com/befriend/detour/domain/invitation/service/InvitationService.java
  src/main/java/com/befriend/detour/domain/schedule/controller/ScheduleController.java
  src/main/java/com/befriend/detour/domain/schedule/dto/EditDateRequestDto.java
  src/main/java/com/befriend/detour/domain/schedule/dto/EditMainImageRequestDto.java
  src/main/java/com/befriend/detour/domain/schedule/dto/EditTitleRequestDto.java
  src/main/java/com/befriend/detour/domain/schedule/dto/ScheduleUpdateRequestDto.java
  src/main/java/com/befriend/detour/domain/schedule/entity/Schedule.java
  src/main/java/com/befriend/detour/domain/schedule/service/ScheduleService.java
  src/main/java/com/befriend/detour/global/exception/ErrorCode.java
Labels: ♻️ refactor, 👾 bug, 🩹 fix

#58 [2024/07/29] feature/schedule/search-get >> 일정 모든 조회, 검색 기능 구현
  http/12. 일정 조회.http
  src/main/java/com/befriend/detour/domain/like/repository/LikeRepositoryCustom.java
  src/main/java/com/befriend/detour/domain/like/repository/LikeRepositoryImpl.java
  src/main/java/com/befriend/detour/domain/schedule/controller/ScheduleController.java
  src/main/java/com/befriend/detour/domain/schedule/dto/ScheduleResponseDto.java
  src/main/java/com/befriend/detour/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/befriend/detour/domain/schedule/repository/ScheduleRepositoryCustom.java
  src/main/java/com/befriend/detour/domain/schedule/repository/ScheduleRepositoryImpl.java
  src/main/java/com/befriend/detour/domain/schedule/service/ScheduleService.java
  src/main/java/com/befriend/detour/global/exception/ErrorCode.java
Labels: ✨ feat

#60 [2024/07/29] feature/user/check-duplicates >> 회원가입 시 중복 확인 관련 코드 구현
  http/1. 회원 가입.http
  src/main/java/com/befriend/detour/domain/user/controller/UserController.java
  src/main/java/com/befriend/detour/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/befriend/detour/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/befriend/detour/domain/user/service/UserService.java
  src/main/java/com/befriend/detour/global/config/SecurityConfig.java
Labels: ✨ feat, ♻️ refactor

#62 [2024/07/30] feature/view >> 조회수 기능 구현
  src/main/java/com/befriend/detour/domain/schedule/dto/ScheduleResponseDto.java
  src/main/java/com/befriend/detour/domain/schedule/entity/Schedule.java
  src/main/java/com/befriend/detour/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/befriend/detour/domain/schedule/service/ScheduleService.java
Labels: ✨ feat

#64 [2024/07/30] refactor/redis >> ec2에 레디스 올리고 프로젝트랑 연결
  docker-compose.yml
  src/main/java/com/befriend/detour/domain/user/service/EmailCertificationService.java
  src/main/java/com/befriend/detour/global/config/RedisConfig.java
  src/main/java/com/befriend/detour/global/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: ♻️ refactor, 🩹 fix

#66 [2024/07/30] feature/jenkins >> Jenkins 관련 환경설정 파일 추가
  Jenkinsfile
  deploy.sh
Labels: ✨ feat

#67 [2024/07/30] feature/jenkins >> Jenkins 관련 환경설정 파일 수정
  Jenkinsfile
Labels: ✨ feat

#68 [2024/07/30] feature/jenkins >> gradle 버전 설정
  Jenkinsfile
Labels: ✨ feat

#69 [2024/07/30] feature/user/auth >> 포트 번호 수정
  src/main/java/com/befriend/detour/global/config/WebSecurityConfig.java
Labels: ✨ feat

#71 [2024/07/31] feature/jenkins>> 권한 설정 및 코드 수정
  Jenkinsfile
  deploy.sh
Labels: ✨ feat

#72 [2024/07/31] feature/jenkins >> 파일 경로 변경
  Jenkinsfile
Labels: ✨ feat

#73 [2024/07/31] feature/view >> 시간별 조회수(hourHit) 추가, 시간별 DB 체크 로직 추가
  src/main/java/com/befriend/detour/DetourApplication.java
  src/main/java/com/befriend/detour/domain/schedule/dto/ScheduleResponseDto.java
  src/main/java/com/befriend/detour/domain/schedule/entity/DBChecker.java
  src/main/java/com/befriend/detour/domain/schedule/entity/Schedule.java
  src/main/java/com/befriend/detour/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/befriend/detour/domain/schedule/service/ScheduleService.java
Labels: ✨ feat

#76 [2024/07/31] feature/jenkins >> 속성 관련 코드 추가
  Jenkinsfile
Labels: ✨ feat

#78 [2024/07/31] feature/social >> 카카오 소셜 로그인 프론트와 연결하기 위해 return 값 수정
  src/main/java/com/befriend/detour/domain/user/controller/UserController.java
  src/main/java/com/befriend/detour/domain/user/service/KakaoService.java
Labels: ✨ feat
