Repository BE-Friend-Develop-Team/detour, pull requests merged in 2024-08, with the labels that each got.

#81 [2024/07/31] feature/redis/ranking >> 랭킹기능 구현
  src/main/java/com/befriend/detour/domain/schedule/dao/RankingDao.java
  src/main/java/com/befriend/detour/domain/schedule/entity/DBChecker.java
  src/main/java/com/befriend/detour/domain/schedule/repository/ScheduleRepositoryCustom.java
  src/main/java/com/befriend/detour/domain/schedule/repository/ScheduleRepositoryImpl.java
  src/main/java/com/befriend/detour/domain/schedule/service/ScheduleService.java
  src/main/resources/application.yml
Labels: ✨ feat

#85 [2024/08/01] feature/user/check-duplicates >> 사용자 정보 업데이트 코드 및 WebSecurityConfig 수정
  src/main/java/com/befriend/detour/domain/user/controller/UserController.java
  src/main/java/com/befriend/detour/domain/user/service/UserService.java
  src/main/java/com/befriend/detour/global/config/WebSecurityConfig.java
Labels: ♻️ refactor

#83 [2024/08/01] feature/schedule/likes >> Like Refactoring
  src/main/java/com/befriend/detour/domain/like/controller/LikeController.java
  src/main/java/com/befriend/detour/domain/like/dto/LikeResponseDto.java
  src/main/java/com/befriend/detour/domain/like/repository/LikeRepository.java
  src/main/java/com/befriend/detour/domain/like/service/LikeService.java
  src/main/java/com/befriend/detour/domain/schedule/controller/ScheduleController.java
  src/main/java/com/befriend/detour/domain/schedule/dto/ScheduleResponseDto.java
  src/main/java/com/befriend/detour/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/befriend/detour/domain/schedule/service/ScheduleService.java
  src/main/java/com/befriend/detour/global/exception/ErrorCode.java
Labels: ♻️ refactor

#91 [2024/08/02] feature/marker/rd >> 이미지 업로드 방식 변경
  http/4. 일정.http
  src/main/java/com/befriend/detour/domain/file/service/FileService.java
  src/main/java/com/befriend/detour/domain/schedule/controller/ScheduleController.java
  src/main/java/com/befriend/detour/domain/schedule/dto/ScheduleUpdateRequestDto.java
  src/main/java/com/befriend/detour/domain/schedule/entity/Schedule.java
  src/main/java/com/befriend/detour/domain/schedule/service/ScheduleService.java
Labels: ♻️ refactor

#93 [2024/08/03] feature/front-schedule >> 일정 response 변경
  src/main/java/com/befriend/detour/domain/dailyplan/dto/DailyPlanResponseDto.java
  src/main/java/com/befriend/detour/domain/dailyplan/entity/DailyPlan.java
  src/main/java/com/befriend/detour/domain/invitation/dto/InvitationResponseDto.java
  src/main/java/com/befriend/detour/domain/marker/dto/MarkerResponseDto.java
  src/main/java/com/befriend/detour/domain/marker/entity/Marker.java
  src/main/java/com/befriend/detour/domain/schedule/dto/ScheduleResponseDto.java
Labels: ✨ feat, ♻️ refactor

#97 [2024/08/06] feature/marker/position1 >> 마커 생성 시 markerIndex 추가
  http/13. 리뷰 작성.http
  src/main/java/com/befriend/detour/domain/marker/controller/MarkerController.java
  src/main/java/com/befriend/detour/domain/marker/dto/MarkerMoveRequestDto.java
  src/main/java/com/befriend/detour/domain/marker/dto/MarkerResponseDto.java
  src/main/java/com/befriend/detour/domain/marker/entity/Marker.java
  src/main/java/com/befriend/detour/domain/marker/repository/MarkerRepositoryCustom.java
  src/main/java/com/befriend/detour/domain/marker/repository/MarkerRepositoryImpl.java
  src/main/java/com/befriend/detour/domain/marker/service/MarkerFileService.java
  src/main/java/com/befriend/detour/domain/marker/service/MarkerService.java
  src/main/java/com/befriend/detour/domain/review/controller/ReviewController.java
  src/main/java/com/befriend/detour/domain/review/dto/ReviewRequestDto.java
  src/main/java/com/befriend/detour/domain/review/dto/ReviewResponseDto.java
  src/main/java/com/befriend/detour/domain/review/entity/Review.java
  src/main/java/com/befriend/detour/domain/review/repository/ReviewRepository.java
  src/main/java/com/befriend/detour/domain/review/service/ReviewService.java
  src/main/java/com/befriend/detour/domain/schedule/controller/ScheduleController.java
  src/main/java/com/befriend/detour/domain/schedule/dao/RankingDao.java
  src/main/java/com/befriend/detour/global/exception/ErrorCode.java
Labels: ✨ feat

#98 [2024/08/06] refactor/front-schedule >> 프론트에 맞춰 로직 수정
  src/main/java/com/befriend/detour/domain/marker/controller/MarkerController.java
  src/main/java/com/befriend/detour/domain/marker/dto/MarkerMoveResponseDto.java
  src/main/java/com/befriend/detour/domain/marker/dto/MarkerResponseDto.java
  src/main/java/com/befriend/detour/domain/marker/service/MarkerService.java
Labels: ♻️ refactor

#99 [2024/08/07] refactor/front-schedule >> 카카오 로그인 수정
  src/main/java/com/befriend/detour/domain/user/controller/UserController.java
  src/main/java/com/befriend/detour/domain/user/service/KakaoService.java
  src/main/java/com/befriend/detour/domain/user/service/UserDetailsServiceImpl.java
Labels: ♻️ refactor

#104 [2024/08/07] refactoring/user/logout >> 카카오톡 로그아웃 기능 구현
  src/main/java/com/befriend/detour/domain/user/controller/UserController.java
  src/main/java/com/befriend/detour/domain/user/service/KakaoService.java
  src/main/java/com/befriend/detour/domain/user/service/UserService.java
Labels: ✨ feat, ♻️ refactor

#106 [2024/08/08] Feature/comment1 >> 댓글 기능
  http/4. 일정.http
  src/main/java/com/befriend/detour/domain/comment/controller/CommentController.java
  src/main/java/com/befriend/detour/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/befriend/detour/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/befriend/detour/domain/comment/entity/Comment.java
  src/main/java/com/befriend/detour/domain/comment/repository/CommentRepository.java
  src/main/java/com/befriend/detour/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/befriend/detour/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/befriend/detour/domain/comment/service/CommentService.java
  src/main/java/com/befriend/detour/domain/schedule/entity/Schedule.java
  src/main/java/com/befriend/detour/global/exception/ErrorCode.java
Labels: ✨ feat

#108 [2024/8/08] feature/review >> 해당 일정 권한 있는 사용자 목록 조회, 리뷰 구현
  http/12. 일정 조회.http
  src/main/java/com/befriend/detour/domain/invitation/controller/InvitationController.java
  src/main/java/com/befriend/detour/domain/invitation/repository/InvitationRepository.java
  src/main/java/com/befriend/detour/domain/invitation/repository/InvitationRepositoryCustom.java
  src/main/java/com/befriend/detour/domain/invitation/repository/InvitationRepositoryImpl.java
  src/main/java/com/befriend/detour/domain/invitation/service/InvitationService.java
  src/main/java/com/befriend/detour/domain/review/controller/ReviewController.java
  src/main/java/com/befriend/detour/domain/review/dto/ReviewRequestDto.java
  src/main/java/com/befriend/detour/domain/review/dto/ReviewResponseDto.java
  src/main/java/com/befriend/detour/domain/review/entity/Review.java
  src/main/java/com/befriend/detour/domain/review/repository/ReviewRepository.java
  src/main/java/com/befriend/detour/domain/review/service/ReviewService.java
Labels: ✨ feat

#110 [2024/08/08] refactoring/schedule/get-schedule >> 페이지 페이지네이션 적용
  src/main/java/com/befriend/detour/domain/schedule/controller/ScheduleController.java
  src/main/java/com/befriend/detour/domain/schedule/service/ScheduleService.java
Labels: ✨ feat, ♻️ refactor

#113 [2024/08/08] feature/review >> 리뷰 content String -> text로 type 변경
  src/main/java/com/befriend/detour/domain/review/entity/Review.java
  src/main/java/com/befriend/detour/domain/review/repository/ReviewRepository.java
  src/main/java/com/befriend/detour/domain/review/service/ReviewService.java
Labels: 🩹 fix

#114 [2024/08/09] refactor/front-schedule >> 페이지네이션 수정
  src/main/java/com/befriend/detour/domain/like/repository/LikeRepositoryCustom.java
  src/main/java/com/befriend/detour/domain/like/repository/LikeRepositoryImpl.java
  src/main/java/com/befriend/detour/domain/schedule/repository/ScheduleRepositoryCustom.java
  src/main/java/com/befriend/detour/domain/schedule/repository/ScheduleRepositoryImpl.java
  src/main/java/com/befriend/detour/domain/schedule/service/ScheduleService.java
Labels: 🩹 fix

#116 [2024/08/09] feature/file >> 파일 확장자 추가(heic)
  src/main/java/com/befriend/detour/domain/file/service/FileService.java
Labels: ✨ feat
